### ISSUE TITLE
website

### ISSUE THREAD

**Issue by massimoalbarello** [Luca8991/FPGAcademyMLG#2]
website to collect audio samples for training set.

## struttura
pagina con autenticazione per registrare samples giusti
pagina libera per registrare samples non necessariamente giusti

**Comment by ilbertt** [comment]
Prima versione del sito disponibile [QUI](https://fpgacademy-mlg.firebaseapp.com/).
Codice sorgente disponibile nella cartella [samples_collector_website](https://github.com/Luca8991/FPGAcademyMLG/tree/master/samples_collector_website)
