### ISSUE TITLE
python download

### ISSUE THREAD

**Issue by massimoalbarello** [Luca8991/FPGAcademyMLG#4]
script per scaricare file .wav da firebase data la lista dei file stessi

**Comment by ilbertt** [comment]
Si possono scaricare tutti i file audio raccolti del bucket di Firebase usando il **gsutil tool** direttamente fornito da Google.

Le istruzioni per usarlo si trovano [qui](https://cloud.google.com/storage/docs/quickstart-gsutil).

In particolare, dopo aver configurato il tool, basta eseguire questo comando
`gsutil cp -r gs://fpgacademy-mlg.appspot.com/true_recs/*.wav .`
per scaricare tutti i file audio nella cartella corrente.
