### ISSUE TITLE
avoid downloading all files every time

### ISSUE THREAD

**Issue by ilbertt** [Luca8991/FPGAcademyMLG#7]
add script to avoid downloading all .wav files from firebase bucket by checking if they are already in the `true_recs` folder.

must be implemented in these modules:

- [create_true_set.py](https://github.com/Luca8991/FPGAcademyMLG/blob/master/python/audio/create_true_set.py)
- [verify_keywords.py](https://github.com/Luca8991/FPGAcademyMLG/blob/master/python/audio/verify_keywords.py)

consider adding a dedicated function in [functions.py](https://github.com/Luca8991/FPGAcademyMLG/blob/master/python/audio/functions.py)

**Comment by gigo333** [comment]
solved with commit  18df50d92b191708d8234b492cae938b970e3810
